version: "2"
run:
  concurrency: 16
  go: "1.24"
  modules-download-mode: mod
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - decorder
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - gocyclo
    - goheader
    - gomodguard
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nilerr
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unused
    - wastedassign
    - forbidigo
    - gomoddirectives
    - usestdlibvars
    - usetesting
    - unconvert

  settings:
    unconvert:
      fast-math: true
      safe: true
    usetesting:
      os-create-temp: true
      os-mkdir-temp: true
      os-setenv: true
      os-temp-dir: true
      os-chdir: true
      context-background: true
      context-todo: true
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
    gomoddirectives:
      replace-local: true
      retract-allow-no-explanation: true
      exclude-forbidden: true
      toolchain-forbidden: true
      go-debug-forbidden: true
      go-version-pattern: '1\.24(\.\d+)?'
      replace-allow-list:
        - github.com/gocql/gocql
    forbidigo:
      analyze-types: true
      forbid:
        - pattern: ^print(ln)?$
          msg: "Use log package instead of fmt"
        - pattern: 'fmt\.Print.*(# Do not commit print statements\.)?'
          msg: "Use log package instead of fmt"
    gocyclo:
      min-complexity: 19
    goheader:
      values:
        regexp:
          spaces: \s+
          two-digits: \d\d
      template: |-
        Copyright 20{{two-digits}} ScyllaDB

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

        {{spaces}}http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    lll:
      line-length: 180
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Error return value of `.*.Unlock` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*.Completed` is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 1000
  max-same-issues: 100
  uniq-by-line: true
formatters:
  enable:
    - gofumpt
    - goimports
    - gci
    - golines
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/scylladb/gemini
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/scylladb/gemini)
      no-inline-comments: true
    golines:
      max-len: 180
      shorten-comments: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
