{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Execution Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Execution Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gemini_execution_time_sum[$__rate_interval])/rate(gemini_execution_time_count[$__rate_interval])",
     "legendFormat": "{{instance}} {{task}}"
    }
   ]
  },
  {
   "title": "TOP K(5)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(increase(gemini_execution_time_count[$__rate_interval])) by (instance, task))\n",
     "legendFormat": "{{instance}} {{task}}"
    }
   ]
  },
  {
   "title": "Number of Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gemini_execution_time_count[$__rate_interval])) by (instance, task)\n",
     "legendFormat": "{{instance}} {{task}}"
    }
   ]
  },
  { "title": "Executed Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Executed CQL Queries",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance, method) (gemini_cql_requests{system=\"test\"})",
     "legendFormat": "{{instance}} - {{method}}"
    }
   ]
  },
  {
   "title": "CQL Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, system, method) (rate(gemini_cql_requests[$__rate_interval]))",
     "legendFormat": "{{instance}} - Cluster({{system}}) Query({{method}})"
    }
   ]
  },
  {
   "title": "Query Timeouts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gemini_cql_timeouts[$__rate_interval])) by (instance, cluster, query_type)",
     "legendFormat": "{{instance}} - {{cluster}} {{query_type}}"
    }
   ]
  },
  {
   "title": "P(50, 90, 99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(gemini_execution_time_bucket[$__rate_interval]))",
     "legendFormat": "{{instance}} P50 {{task}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(gemini_execution_time_bucket[$__rate_interval]))",
     "legendFormat": "{{instance}} P90 {{task}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(gemini_execution_time_bucket[$__rate_interval]))",
     "legendFormat": "{{instance}} P99 {{task}}"
    }
   ]
  },
  { "title": "Partitions / Value Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Partition Filled Event",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (instance, table) (gemini_generated_filled_partitions)",
     "legendFormat": "{{instance}} - {{table}}"
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gemini_generated_buffer_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemini_generated_partition_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stale Partition Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gemini_stale_partitions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage Per Generator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance,type,context) (gemini_memory_footprint{type=\"generator\"})",
     "legendFormat": "{{instance}} - {{context}}"
    }
   ]
  },
  {
   "title": "Values available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by(instance, type, context) (\n    rate(gemini_channel_size{type=\"generator\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}} - {{context}}"
    }
   ]
  },
  {
   "title": "Values Generated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by (instance, table) (\n  rate(gemini_generated_emitted_values[$__rate_interval])\n)",
     "legendFormat": "{{instance}} - {{table}}"
    }
   ]
  },
  {
   "title": "Dropped Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by (instance, table, type) (rate(gemini_generated_dropped_values[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{table}} {{type}}"
    }
   ]
  },
  { "title": "GoCQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (cluster, query, instance)(rate(gemini_cql_query_time_bucket{cluster=\"test_cluster\",query=~\"InsertStatement|SelectStatement|UpdateStatement|DeleteStatement\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} {{query}}"
    }
   ]
  },
  {
   "title": "Oracle Cluster Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemini_cql_connections{host=~\".+\", cluster=\"oracle_cluster\"}",
     "legendFormat": "{{instance}} - {{host}}"
    }
   ]
  },
  {
   "title": "Oracle Cluster Average Connection Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemini_cql_connect_time_sum{cluster=\"oracle_cluster\"} / gemini_cql_connect_time_count{cluster=\"oracle_cluster\"}",
     "legendFormat": "{{instance}} - {{host}} {{cluster}}"
    }
   ]
  },
  {
   "title": "Test Cluster Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemini_cql_connections{host=~\".+\", cluster=~\"test_cluster\"}",
     "legendFormat": "{{instance}} - {{host}}"
    }
   ]
  },
  {
   "title": "Test Cluster Average Connection Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemini_cql_connect_time_sum{cluster=\"test_cluster\"} / gemini_cql_connect_time_count{cluster=\"test_cluster\"}",
     "legendFormat": "{{instance}} - {{host}} {{cluster}}"
    }
   ]
  },
  {
   "title": "Queries Executed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "targets": [
    {
     "expr": "sum by(instance, query_type) (rate(gemini_cql_queries[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{query_type}}"
    }
   ]
  },
  {
   "title": "AVG Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(gemini_cql_query_time_sum{cluster=\"test_cluster\"}[$__rate_interval]) / rate(gemini_cql_query_time_count{cluster=\"test_cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "rate(gemini_cql_query_errors[$__rate_interval])",
     "legendFormat": "{{instance}} - {{cluster}} {{error}} {{query}}"
    }
   ]
  },
  { "title": "General Gemini", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(gemini_go_gc_duration_seconds_sum[$__rate_interval]) / rate(gemini_go_gc_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(gemini_process_cpu_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Reclaimed Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(rate(gemini_go_memstats_frees_total[$__rate_interval]) * (gemini_go_memstats_alloc_bytes / gemini_go_memstats_mallocs_total))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Stack Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(gemini_go_memstats_stack_inuse_bytes[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(gemini_process_virtual_memory_bytes[$__rate_interval])",
     "legendFormat": "Virtual Memory - {{instance}}"
    },
    {
     "expr": "rate(gemini_go_memstats_heap_idle_bytes[$__rate_interval])",
     "legendFormat": "Heap Idle {{instance}}"
    },
    {
     "expr": "rate(gemini_go_memstats_heap_alloc_bytes[1m])",
     "legendFormat": " Heap Allocated {{ instance }}"
    },
    {
     "expr": "rate(gemini_go_memstats_alloc_bytes[$__rate_interval])",
     "legendFormat": "Allocated {{instance}}"
    },
    {
     "expr": "rate(gemini_process_resident_memory_bytes[$__rate_interval])",
     "legendFormat": "Resident Memory {{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "gemini_go_goroutines{instance=~\".*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Instance Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 109 },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance=\"gemini\", job=~\"node_exporter.*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CQL Statement Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "File Size Grow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, file) (rate(gemini_file_size_bytes[$__rate_interval]))",
     "legendFormat": "{{instance}} {{file}}"
    }
   ]
  },
  {
   "title": "File Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance, file) (gemini_file_size_bytes)",
     "legendFormat": "{{instance}} - {{file}}"
    }
   ]
  },
  {
   "title": "Memory Usage Per Statement Logger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance,type,context) (gemini_memory_footprint{type=\"statement_logger\"})",
     "legendFormat": "{{instance}} - {{context}}"
    }
   ]
  },
  {
   "title": "Values available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "sum by(instance, type, context) (\n    rate(gemini_channel_size{type=\"statement_logger\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}} - {{context}}"
    }
   ]
  }
 ]
}