networks:
  gemini:
    name: gemini
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24

services:
  gemini-oracle:
    image: scylladb/scylla:${SCYLLA_ORACLE_VERSION:-6.2}
    container_name: gemini-oracle
    restart: unless-stopped
    command: --smp 1 --memory 1024M --api-address 0.0.0.0
    networks:
      gemini:
        ipv4_address: 192.168.100.2

  gemini-test:
    image: scylladb/scylla:${SCYLLA_TEST_VERSION:-6.2}
    container_name: gemini-test
    restart: unless-stopped
    command: --smp 1 --memory 1024M --api-address 0.0.0.0
    networks:
      gemini:
        ipv4_address: 192.168.100.3
